name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: cache
      with:
        path: '.emsdk-cache'
        key: emscripten-2.0.6
    - uses: mymindstorm/setup-emsdk@ca33dc66a6b178f65393989c12e9465baf053352
      with:
        version: '2.0.6'
        actions-cache-folder: '.emsdk-cache'
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with: {name: dist, path: dist}
    - name: test
      run: npm ci && npm test
    - name: generate documentation
      run: npm run doc
    - name: Update github pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: "." # The folder the action should deploy.
        CLEAN: false # Automatically remove deleted files from the deploy branch
